# Generated by Django 5.2.9 on 2026-01-03 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpVisitRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='访问时间')),
                ('ip_address', models.CharField(max_length=50, verbose_name='访问者IP')),
            ],
            options={
                'verbose_name': 'IP访问记录',
                'verbose_name_plural': 'IP访问记录',
                'ordering': ['-visit_time'],
            },
        ),
    ]
