# Generated by Django 5.2.9 on 2026-03-01 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0002_userprofile_delete_ipvisitrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='药品名称')),
                ('description', models.TextField(blank=True, verbose_name='药品描述')),
                ('dosage', models.CharField(max_length=100, verbose_name='服用剂量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '药品信息',
                'verbose_name_plural': '药品信息',
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='服用时间')),
                ('frequency_type', models.CharField(choices=[('morning', '早晨'), ('noon', '中午'), ('evening', '晚上'), ('custom', '自定义')], max_length=20, verbose_name='频次类型')),
                ('days_of_week', models.CharField(default='1,2,3,4,5,6,7', max_length=20, verbose_name='适用星期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='zapp.medication', verbose_name='药品')),
            ],
            options={
                'verbose_name': '用药计划',
                'verbose_name_plural': '用药计划',
            },
        ),
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='记录日期')),
                ('status', models.CharField(choices=[('taken', '已服用'), ('missed', '未服用'), ('skipped', '跳过')], default='missed', max_length=20, verbose_name='状态')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='实际服用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='zapp.medicationschedule', verbose_name='关联计划')),
            ],
            options={
                'verbose_name': '用药记录',
                'verbose_name_plural': '用药记录',
                'unique_together': {('schedule', 'date')},
            },
        ),
    ]
