# Generated by Django 5.2.9 on 2026-03-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0003_medication_medicationschedule_medicationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='current_quantity',
            field=models.IntegerField(default=0, verbose_name='当前剩余量'),
        ),
        migrations.AddField(
            model_name='medication',
            name='total_quantity',
            field=models.IntegerField(default=0, verbose_name='初始总量'),
        ),
        migrations.AddField(
            model_name='medication',
            name='unit',
            field=models.CharField(default='片', max_length=20, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='dosage_amount',
            field=models.IntegerField(default=1, verbose_name='每次服用数量'),
        ),
    ]
