# Generated by Django 5.2.9 on 2026-03-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0004_medication_current_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='设备名称')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, verbose_name='最后心跳时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('status', models.CharField(default='offline', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '设备监控',
                'verbose_name_plural': '设备监控',
            },
        ),
    ]
