# Generated by Django 5.2.9 on 2026-03-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0005_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间'),
        ),
    ]
